web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - web.concourse-pks-helm.pks.gcp-nonprod.arg-pivotal.com
    tls:
    - hosts:
      - web.concourse-pks-helm.pks.gcp-nonprod.arg-pivotal.com
      secretName: concourse-external-cert
