---
image: agregory99/concourse
imageTag: 5.5.6-ubuntu
concourse:
  web:
    externalUrl: http://concourse.ingress.aks.arg-pivotal.com
web:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod-azure-dns"
      kubernetes.io/ingress.class: nginx
    hosts:
      - concourse.ingress.aks.arg-pivotal.com
    tls:
      - hosts:
        - concourse.ingress.aks.arg-pivotal.com
        secretName: concourse-external-cert
worker:
  replicas: 3
  nodeSelector:
    agentpool: nodepoolb2ms
  hardAntiAffinity: true
postgresql:
  image:
    registry:
    repository: agregory99/postgres
    tag: 0.0.1
persistence:
  worker:
    size: 100Gi
